### ISSUE TITLE
The build speed

### ISSUE THREAD

**Issue by LNeway** [touchlab/KotlinCocoapods#14]
When I change the Kotlin native code , it will cost a lot of time to finish the build task (Xcode)

task named :shared:linkDebugFrameworkIos  will cost about two minutes 

any advice to improve the build speed ?

**Comment by LNeway** [comment]
the host is MacBook Pro (15-inch, 2019)

**Comment by russhwolf** [comment]
This isn't really in scope of this plugin. Linking speed is about the kotlin compiler itself. It's not perfect right now, but JetBrains is working on it!
