### ISSUE TITLE
Ability To Update Framework Name

### ISSUE THREAD

**Issue by markrebhan** [touchlab/KotlinCocoapods#8]
It would be nice if the `frameworkName` attribute was exposed as a mutable field like the jetbrains version. It's kind of annoying that the framework is just called `shared` in XCode and having `import shared` is a bit ambiguous in the source code.

**Comment by russhwolf** [comment]
We adjusted it so that you can access the entire framework configuration from a `framework` block inside `cocoapodsext`. Does this do what you want?
```kotlin
cocoapodsext {
  framework {
    baseName = "MyFramework"
  }
}
```

**Comment by markrebhan** [comment]
Yes, that is what I was looking for. Much appreciated.
